### ISSUE TITLE
[CI] Adicionar Github Actions

### ISSUE THREAD

**Issue by gondekr** [ingresse/android-sdk#137]
# Descrição
Adicionar workflow básico do github actions com teste executado pelo gradle

## Requisitos
Máquina: ```ubuntu-latest```
Versão do Java: ```1.8```

## Sintaxe de exemplo
```yml
name: Run Tests
on: [push]
jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle test
      run: gradlew test
```
